spring:
  application:
    name: demo
  h2.console.enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          # Replace with the domain of your Auth0 tenant.
          # Note the trailing slash is important!
          issuer-uri: https://dev-ctcnhqpj.us.auth0.com/

debug: false

server:
  port: 3000
  servlet:
    context-path: /

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
  file: fxDeals.log
  path: /app/demo/logs/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

auth0:
  # Replace with the API Identifier for your Auth0 API.
  audience: https://demo/api


