spring:
  application:
    name: demo
  h2.console.enabled: true
  web.resources.static-locations: classpath:/web/
  security:
    oauth2:
      resourceserver:
        jwt:
          # Replace with the domain of your Auth0 tenant.
          # Note the trailing slash is important!
          issuer-uri: https://dev-ctcnhqpj.us.auth0.com/

debug: false

server:
  port: 3000
  servlet:
    context-path: /

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG
  file: fxDeals.log
  path: /app/demo/logs/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

auth0:
  # Replace with the API Identifier for your Auth0 API.
  audience: https://demo/api

stripe:
  keys:
    public: "pk_test_51JmI6pIqCcvOBL6BSMUyoR8vDRh0sTArvvQ4tBIrSirskZMNZiCVTrH654vCWDtlQka5pqAH2Ma0Q2DC1a6t5jjK00dXiDxOUB"
    private: "sk_test_51JmI6pIqCcvOBL6BHeIcZXLwpcwtDCCaJcF0WBVUOdOzG9MHXMYpl2KLvwtivUURLkI2UvAx471xrukNaFHj5zgB00mFxkNMW2"
